default: 
  image: python:3.9
  before_script:
  - pip install -e .[dev]

run tests:
  stage: test
  services:
    - name: ${POD_IMAGE}
      alias: pod
      entrypoint:
        - "/pod"
        - "--owners=ANY"
        - "--insecure-non-tls=0.0.0.0"
        - "--plugin-auth-key=9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"
  script:
  - curl http://pod:3030/version
  - export POD_ADDRESS='http://pod:3030'
  - pre-commit run --all-files
  - pytest --cov=pymemri tests 


memri-docs:
  stage: deploy
  only:
    - dev
  trigger: memri/docs.memri.io

release_to_pypi:
  stage: deploy
  only:
    - tags
  script:
    - version=v$(python setup.py --version)
    - |
      if [[ "${CI_COMMIT_TAG}" != "${version}" ]]; then
          echo "Tag '${CI_COMMIT_TAG}' does not match the expected version '${version}'"
          exit 1
      fi
    - echo "OK"
    - TWINE_USERNAME=__token__ TWINE_PASSWORD=${PYPI_TOKEN} make release
