default: 
  image: python:3.7
  before_script:
  - pip install -e .[dev]

run tests:
  stage: test
  services:
    - name: ${POD_IMAGE}
      alias: pod
      entrypoint:
        - "/pod"
        - "--owners=ANY"
        - "--insecure-non-tls=0.0.0.0"
  script:
  - curl http://pod:3030/version
  - export POD_ADDRESS='http://pod:3030'
  - pre-commit run --all-files
  - pytest


memri-docs:
  stage: deploy
  only:
    - dev
  trigger: memri/docs.memri.io

release_to_pypi:
  stage: deploy
  only:
    - tags
  script:
    - version=$(python setup.py --version)
    - |
      if [[ "${CI_COMMIT_TAG}" != v"${version}" ]]; then
          echo "Tag '${CI_COMMIT_TAG}' does not match the expected version '${version}'"
          exit 1
      fi
    - echo "OK"
    - make dist
    - make test_release
