default: 
  image: python:3.7
  before_script:
  - apt-get update && apt-get install -y libsqlcipher-dev && apt-get install -y libgl1-mesa-glx
  - pip install -e .[dev]


run tests:
  stage: test
  services:
    - name: ${POD_IMAGE}
      alias: pod
      entrypoint:
        - "/pod"
        - "--owners=ANY"
        - "--insecure-non-tls=0.0.0.0"
  script:
  - curl http://pod:3030/version
  - export POD_ADDRESS='http://pod:3030'
  - ./tools/test_in_ci.sh

# pages:
#   only:
#     - dev
#   inherit:
#     default: false
#   image: ruby:2.7
#   stage: deploy  
#   before_script: 
#   script:
#   - cd docs
#   - bundle install
#   - bundle exec jekyll build -d ../public
#   artifacts:
#     paths:
#     - public

# memri-docs:
#   stage: deploy
#   only:
#     - dev
#   trigger: memri/docs.memri.io
