default: 
  image: python:3.7
  before_script:
  - pip install -e .[dev]

run pre-commit:
  stage: test
  script:
  - pre-commit run --all-files

run tests:
  stage: test
  services:
    - name: ${POD_IMAGE}
      alias: pod
      entrypoint:
        - "/pod"
        - "--owners=ANY"
        - "--insecure-non-tls=0.0.0.0"
  script:
  - curl http://pod:3030/version
  - export POD_ADDRESS='http://pod:3030'
  - pytest


memri-docs:
  stage: deploy
  only:
    - dev
  trigger: memri/docs.memri.io
