# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/plugin.listeners.ipynb (unless otherwise specified).

__all__ = ['status_listener', 'abort_plugin_callback', 'get_abort_plugin_listener']

# Cell

import time
import os
import signal
from threading import Thread

# Cell
def status_listener(client, run_id, status, callback, interval=5, verbose=False):
    """
    Listens to status field of plugin, and executes callback when run.status == status.
    """
    if verbose:
        print(f"Listening for status='{status}' on Item {run_id}")
    while True:
        time.sleep(interval)
        try:
            run = client.get(run_id)
            if verbose:
                print("run status:", run.status)
            if run.status == status:
                callback()
        except Exception as e:
            print(f"Could not get run in status listener: {e}")

# Cell
def abort_plugin_callback():
    print("Status aborted, killing plugin...")
    pid = os.getpid()
    os.kill(pid, signal.SIGABRT)

def get_abort_plugin_listener(client, run_id, **kwargs):
    listener = Thread(
        target=status_listener,
        args=(client, run_id, "aborted", abort_plugin_callback),
        kwargs=kwargs
    )
    listener.start()
    return listener