# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/plugin.states.ipynb (unless otherwise specified).

__all__ = ['RUN_IDLE', 'RUN_INITIALIZED', 'RUN_USER_ACTION_NEEDED', 'RUN_USER_ACTION_COMPLETED', 'RUN_STARTED',
           'RUN_FAILED', 'RUN_COMPLETED']

# Cell

# run states
RUN_IDLE = 'idle'                           #1
RUN_INITIALIZED = 'initilized'              #2
RUN_USER_ACTION_NEEDED = 'userActionNeeded' # 2-3
RUN_USER_ACTION_COMPLETED = 'ready'         # 2-3
RUN_STARTED = 'start'                       #3
RUN_FAILED = 'error'                        # 3-4
RUN_COMPLETED = 'done'                      #4